name: alnoor
description: "A new Flutter project."
publish_to: "none"

version: 2.0.3+6

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  fluttertoast: ^8.2.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.0.3
  cloud_firestore: ^5.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  icons_plus: ^5.0.0
  carousel_slider: ^4.2.1
  ticket_widget: ^1.0.2
  flutter_credit_card: ^4.0.1
  cryptlib_2_0: ^0.0.3
  image_pickers: ^2.0.5+2
  file_picker: ^8.0.6
  csv: ^6.0.0
  webview_flutter: ^4.8.0
  http: ^1.2.1
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: any
  webview_flutter_web: ^0.2.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/icons/
