// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtjzC3bQrbfupgNJEscYLPvJhVbBsydNw',
    appId: '1:114679571707:web:37456e620150121476bc5e',
    messagingSenderId: '114679571707',
    projectId: 'alnoorcomma',
    authDomain: 'alnoorcomma.firebaseapp.com',
    storageBucket: 'alnoorcomma.appspot.com',
    measurementId: 'G-N22XF3WZ66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8aBzMytEUMiJ6WeRv_gxXW7lioUHCSM8',
    appId: '1:114679571707:android:fab77fa4601c164776bc5e',
    messagingSenderId: '114679571707',
    projectId: 'alnoorcomma',
    storageBucket: 'alnoorcomma.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ3fYTL2KuXMMCD10Qo6CBMmZBnjvVGs8',
    appId: '1:114679571707:ios:678d457a4e643efa76bc5e',
    messagingSenderId: '114679571707',
    projectId: 'alnoorcomma',
    storageBucket: 'alnoorcomma.appspot.com',
    iosBundleId: 'com.comma.alnooralsate',
  );
}
